// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5sGyhhuGuUX5wnChH8uZNJxnmf_xy1z0',
    appId: '1:525541211178:web:c8e975c11fe15e050dd753',
    messagingSenderId: '525541211178',
    projectId: 'skillzuppsofts',
    authDomain: 'skillzuppsofts.firebaseapp.com',
    storageBucket: 'skillzuppsofts.appspot.com',
    measurementId: 'G-X8HJRDFN41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6i6P85aGJm3zPIuXdRuu4_Mue6Z9e6kg',
    appId: '1:525541211178:android:0ea7cd39c34d76180dd753',
    messagingSenderId: '525541211178',
    projectId: 'skillzuppsofts',
    storageBucket: 'skillzuppsofts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX_avinwUVZOlM25YuzBTEyG9T4WA2vs0',
    appId: '1:525541211178:ios:3248aeb91d86a8c60dd753',
    messagingSenderId: '525541211178',
    projectId: 'skillzuppsofts',
    storageBucket: 'skillzuppsofts.appspot.com',
    iosBundleId: 'com.example.cafepos',
  );
}
